### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by ghost** [vincentbernat/nixops-take1#1]
### Thank you (Not an Issue)

I just solved my utf-8 charaters issue with these codes and I wanted to thank you for sharing. It was long day for me... 🙏

https://github.com/vincentbernat/nixops-take1/blob/e0cc6079d140895a2ef5157e6641ab06468863e7/web.nix#L238-L253

**Comment by vincentbernat** [comment]
Glad it was useful to you!
